// import { Amplify } from 'aws-amplify';
// import { generateClient } from 'aws-amplify/data';
// import type { Schema } from '../../amplify/data/resource';
// import outputs from '../../amplify_outputs.json';

// /**
//  * Amplify runtime wiring for the SPA.
//  *
//  * `amplify_outputs.json` is generated by `npx ampx sandbox` (or the pipeline
//  * build) and is git-ignored — it carries the environment-specific Cognito /
//  * AppSync / S3 identifiers for whichever backend you deployed. Configuration is
//  * a module side effect so it runs once, at import time; `main.tsx` imports this
//  * module first, before anything renders.
//  *
//  * `client` is the single typed GraphQL client the app shares. Feature code
//  * (CRIS-6 report form, CRIS-12 dashboard, …) imports it and calls the schema's
//  * models / custom operations with full type-safety, e.g.
//  * `client.mutations.submitReport({ text, clientRequestId })`.
//  */
// Amplify.configure(outputs);

// export const client = generateClient<Schema>();


export const client = {
  models: {},
  queries: {},
  mutations: {},
};